apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: my-service
  description: A description of the service
  tags:
    - service
spec:
  type: service
  owner: team-a
  lifecycle: production
